name: Widgets Library

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Allow writing to repository contents (e.g., pushing to gh-pages)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
  
      - name: Run tests with coverage
        run: npm run test

      - name: Generate coverage badge
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage-summary.json
          output: coverage/badges.svg

      - name: Deploy badge to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
  
      - name: Build the library
        run: npm run build

      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}