name: Deploy Site to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'site/**'  # Trigger only on changes to site/ folder and subdirectories
  workflow_dispatch:  # Still allow manual runs

permissions:
  contents: write  # Grant write access to repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
          cname: dappify.com  # Replace with your custom domain